repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.6.1
    hooks:
      - id: golangci-lint
        args: ["--new-from-rev", "HEAD", "--skip-dirs", "internal/store"] # Temporarily skip internal/store tests

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0 # Use a recent stable version
    hooks:
      - id: hadolint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
  - repo: local
    hooks:
      - id: go-vet
        name: go vet
        entry: ./scripts/run-go-vet.sh
        language: system
      - id: go-test
        name: go test
        entry: go test ./internal/api ./internal/service
        language: system
        pass_filenames: false
        types: [go]
      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
        types: [go]
      - id: gosec
        name: gosec
        entry: gosec ./...
        language: system
        pass_filenames: false
        types: [go]
